'use client';
import {useEffect,useState} from 'react';
import {Button,toast} from '@/components/ui';
import {DEFAULT_STEPS} from '@/lib/production/bom';
import {readJson,useWorkflowMutation,fieldClass} from './client';
export function OrderDraft({meta,projectId,order,onSaved}:{meta:any;projectId:string;order?:any;onSaved:(id:string)=>void}){
 const [title,setTitle]=useState(order?.title || ''),[dueAt,setDueAt]=useState(order?.due_at?new Date(new Date(order.due_at).getTime()-new Date(order.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):''),[sourceWarehouse,setSourceWarehouse]=useState(''),[parentTaskId,setParentTaskId]=useState(''),[tasks,setTasks]=useState<any[]>([]),[lines,setLines]=useState<any[]>([]);
 const {busy,mutate,run}=useWorkflowMutation();
 useEffect(()=>{if(order)setLines(order.lines.map((l:any)=>({id:l.id,bomId:l.bom_id,title:l.title,outputItemId:l.output_item_id,unitId:l.unit_id,teamId:l.team_id,targetQty:Number(l.target_qty),bomYieldQty:Number(l.bom_yield_qty),hasElectrical:l.has_electrical,steps:l.steps.map((s:any)=>s.title),sourceWarehouseId:l.materials[0]?.source_warehouse_id || '',materialWarehouses:Object.fromEntries(l.materials.map((m:any)=>[m.item_id,m.source_warehouse_id])),materials:l.snapshot.bom.expanded || []})));},[order]);
 useEffect(()=>{if(projectId)setTasks((meta.tasks || []).filter((t:any)=>t.project_id===projectId));},[projectId,meta.tasks]);
 const update=(i:number,v:any)=>setLines(ls=>ls.map((l,n)=>n===i?{...l,...v}:l));
 const add=async(id:string)=>{if(!id||lines.some(l=>l.bomId===id))return;const {bom}=await readJson(`/api/bom/${id}/production`);if(bom.needsMapping)throw new Error('Hoàn thiện gán BOM trước khi lập lệnh');setLines(ls=>[...ls,{bomId:id,title:bom.title,outputItemId:'',unitId:'',teamId:'',targetQty:1,bomYieldQty:1,hasElectrical:false,steps:[...DEFAULT_STEPS],sourceWarehouseId:sourceWarehouse,materialWarehouses:{},materials:bom.expanded}]);};
 return <div className="space-y-3 text-xs">
  <div className="grid md:grid-cols-3 gap-3"><label>Tên lệnh<input className={fieldClass} aria-label="Tên lệnh" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Hạn hoàn thành<input className={fieldClass} type="datetime-local" aria-label="Hạn hoàn thành" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>Kho NVL mặc định<select className={fieldClass} aria-label="Kho NVL mặc định" value={sourceWarehouse} onChange={e=>{setSourceWarehouse(e.target.value);setLines(ls=>ls.map(l=>({...l,sourceWarehouseId:e.target.value})));}}><option value="">Chọn kho</option>{meta.warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div>
  {!order && <div className="grid md:grid-cols-2 gap-3"><label>Thêm BOM đã gán<select aria-label="Thêm BOM" className={fieldClass} value="" onChange={e=>run(()=>add(e.target.value))}><option value="">Chọn BOM của dự án</option>{meta.boms.filter((b:any)=>b.project_id===projectId && b.mapped && !lines.some(l=>l.bomId===b.id)).map((b:any)=><option key={b.id} value={b.id}>{b.code} · {b.title}</option>)}</select></label><label>Gắn dưới công việc WBS<select aria-label="Công việc WBS" className={fieldClass} value={parentTaskId} onChange={e=>setParentTaskId(e.target.value)}><option value="">Tạo nhánh sản xuất riêng trong dự án</option>{tasks.map((t:any)=><option key={t.id} value={t.id}>{t.code} · {t.title}</option>)}</select></label></div>}
  {!lines.length && <p className="text-slate-500 p-3 border rounded">Chọn BOM đã gán để thêm các hạng mục sản xuất.</p>}
  {lines.map((l,i)=>{const product=meta.items.find((p:any)=>p.id===l.outputItemId);return <section key={l.id || l.bomId} className="border rounded p-3 space-y-2">
   <div className="flex justify-between items-center"><strong>{i+1}. {l.title}</strong>{!order && <Button size="sm" variant="ghost" onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))}>Bỏ hạng mục</Button>}</div>
   <div className="grid md:grid-cols-4 gap-2"><label>Thành phẩm đại diện<select aria-label={`Thành phẩm ${i+1}`} className={fieldClass} value={l.outputItemId} onChange={e=>{const p=meta.items.find((v:any)=>v.id===e.target.value);update(i,{outputItemId:e.target.value,unitId:p?.baseUnitId || ''});}}><option value="">Chọn mã chung</option>{meta.items.filter((p:any)=>p.isActive && ['product','semi_finished'].includes(p.kind)).map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label>
    <label>Đơn vị thành phẩm<select className={fieldClass} aria-label={`Đơn vị thành phẩm ${i+1}`} value={l.unitId} onChange={e=>update(i,{unitId:e.target.value})}><option value="">Chọn đơn vị</option>{product?.conversions.map((u:any)=><option key={u.unitId} value={u.unitId}>{u.unitName}</option>)}</select></label>
    <label>Sản lượng cần làm<input className={fieldClass} aria-label={`Sản lượng ${i+1}`} type="number" min="0.000001" step="any" value={l.targetQty} onChange={e=>update(i,{targetQty:Number(e.target.value)})}/></label>
    <label>BOM đang tính cho sản lượng<input className={fieldClass} aria-label={`Sản lượng BOM ${i+1}`} type="number" min="0.000001" step="any" value={l.bomYieldQty} onChange={e=>update(i,{bomYieldQty:Number(e.target.value)})}/></label>
    <label>Nhóm phụ trách<select className={fieldClass} aria-label={`Nhóm ${i+1}`} value={l.teamId} onChange={e=>update(i,{teamId:e.target.value})}><option value="">Chọn nhóm xưởng</option>{meta.teams.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
    <label className="flex items-center gap-2"><input type="checkbox" aria-label={`Có điện ${i+1}`} checked={l.hasElectrical} onChange={e=>update(i,{hasElectrical:e.target.checked})}/>Có điện / LED</label>
   </div>
   <label className="block">Công đoạn theo thứ tự (mỗi dòng một công đoạn, dòng cuối là QC)<textarea className={`${fieldClass} h-24`} aria-label={`Công đoạn ${i+1}`} value={l.steps.join('\n')} onChange={e=>update(i,{steps:e.target.value.split('\n')})}/></label>
   <table className="w-full"><thead className="bg-slate-50"><tr><th className="text-left p-1">NVL triển khai</th><th>Cần (đơn vị cơ sở)</th><th className="text-left">Kho cấp</th></tr></thead><tbody>{l.materials.map((m:any)=>{const item=meta.items.find((v:any)=>v.id===m.itemId);return <tr key={m.itemId} className="border-b"><td className="p-1">{item?.code} · {item?.name}</td><td className="text-center">{Number((m.baseQty*l.targetQty/l.bomYieldQty).toFixed(6))}</td><td className="p-1"><select aria-label={`Kho ${i+1} ${item?.code}`} className={fieldClass} value={l.materialWarehouses[m.itemId] || l.sourceWarehouseId || sourceWarehouse} onChange={e=>update(i,{materialWarehouses:{...l.materialWarehouses,[m.itemId]:e.target.value}})}><option value="">Chọn kho</option>{meta.warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></td></tr>;})}</tbody></table>
  </section>;})}
  <div className="flex justify-end"><Button disabled={busy || !lines.length} onClick={()=>run(async()=>{const data={projectId,title,dueAt:dueAt?new Date(dueAt).toISOString():null,parentTaskId:parentTaskId || undefined,sourceWarehouseId:sourceWarehouse,lines:lines.map(({materials,...l})=>l)};const r=await mutate(order?`/api/production-orders/${order.id}/actions`:'/api/production-orders',order?{...data,action:'edit_draft'}:data);toast.success('Đã lưu lệnh nháp; gửi duyệt để tạo phiếu xuất NVL');onSaved(r.orderId);})}>Lưu lệnh nháp</Button></div>
 </div>;
}
