'use client';
import {useState} from 'react';
import {toast} from '@/components/ui';
async function photoData(file:File){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Chọn ảnh JPG, PNG hoặc WebP không quá 5 MB');
 const url=URL.createObjectURL(file);try{const picture=new Image();await new Promise<void>((resolve,reject)=>{picture.onload=()=>resolve();picture.onerror=()=>reject(new Error('Không đọc được ảnh'));picture.src=url;});const scale=Math.min(1,1600/Math.max(picture.width,picture.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(picture.width*scale));canvas.height=Math.max(1,Math.round(picture.height*scale));canvas.getContext('2d')!.drawImage(picture,0,0,canvas.width,canvas.height);const encoded=canvas.toDataURL('image/jpeg',.8);if(encoded.length>1024*1024)throw new Error('Ảnh quá lớn; chọn ảnh nhỏ hơn');return encoded;}finally{URL.revokeObjectURL(url);}
}
export function PhotosField({value,onChange,onBusyChange}:{value:string;onChange:(v:string)=>void;onBusyChange?:(busy:boolean)=>void}){
 const [loading,setLoading]=useState(false),photos=value.split('\n').filter(Boolean);
 return <div className="space-y-2"><label className="block">Ảnh công đoạn / QC<input aria-label="Ảnh công đoạn QC" className="block mt-1 text-xs" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={loading} onChange={async e=>{const files=Array.from(e.target.files || []);e.target.value='';setLoading(true);onBusyChange?.(true);try{if(files.length+photos.length>20)throw new Error('Tối đa 20 ảnh mỗi lần ghi');const urls=[...photos];for(const file of files)urls.push(await photoData(file));if(urls.join('').length>3*1024*1024)throw new Error('Tổng ảnh vượt giới hạn; chia thành các lần ghi nhật ký');onChange(urls.join('\n'));}catch(e:any){toast.error(e.message);}finally{setLoading(false);onBusyChange?.(false);}}}/></label>{loading && <span>Đang chuẩn bị ảnh…</span>}<div className="flex gap-2 flex-wrap">{photos.map((url,n)=><div key={`${url.slice(0,80)}-${n}`} className="relative"><img src={url} alt={`Ảnh ${n+1}`} className="h-20 w-24 object-cover rounded border"/><button type="button" aria-label={`Bỏ ảnh ${n+1}`} className="absolute top-0 right-0 bg-white px-1 rounded text-red-600" onClick={()=>onChange(photos.filter((_,i)=>i!==n).join('\n'))}>×</button></div>)}</div></div>;
}
