'use client';
import Link from 'next/link';
import {Button,toast} from '@/components/ui';
import {useWorkflowMutation,statusLabels} from './client';
export function StockDocuments({documents,capabilities,onChanged}:{documents:any[];capabilities:any;onChanged:()=>Promise<void>}){
 const {busy,mutate,run}=useWorkflowMutation();
 const names:any={production_material:'Cấp NVL',production_return:'Trả NVL',production_output:'Nhập thành phẩm',sales_fulfillment:'Xuất bán',reversal:'Đảo chứng từ'};
 return <div className="overflow-x-auto border rounded"><table className="w-full text-xs"><thead className="bg-slate-100"><tr>{['Phiếu kho','Loại','Trạng thái','Thao tác'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{documents.map(d=><tr key={d.id} className="border-t"><td className="p-2"><Link className="text-blue-600" href={`/kho/nhap-xuat?documentId=${d.id}`}>{d.code}</Link></td><td className="p-2">{names[d.workflow_kind] || d.type}</td><td className="p-2">{statusLabels[d.status] || d.status}</td><td className="p-2 flex flex-wrap gap-1">{[['approve','Duyệt',d.status==='submitted',capabilities['stock_document.approve']],['complete','Xác nhận thực tế',d.status==='approved',capabilities['stock_document.post'] || capabilities['stock_document.complete']],['cancel','Hủy phiếu',['draft','submitted','approved'].includes(d.status),capabilities['stock_document.cancel']],['reverse','Lập phiếu đảo',d.status==='completed' && d.workflow_kind!=='reversal',capabilities['stock_document.reverse'] && capabilities['stock_document.create']]].map(([action,label,eligible,can])=>eligible && can && <Button key={String(action)} size="sm" variant="secondary" disabled={busy} onClick={()=>run(async()=>{await mutate(action==='cancel'?`/api/inventory/documents/${d.id}`:`/api/inventory/documents/${d.id}/${action}`,{},action==='cancel'?'DELETE':'POST');toast.success('Đã xử lý phiếu kho');await onChanged();})}>{String(label)}</Button>)}</td></tr>)}</tbody></table>{!documents.length && <p className="p-3 text-slate-500">Chưa phát sinh phiếu kho.</p>}</div>;
}
