'use client';
import {useSetPageHeader} from '@/contexts/page-header-context';
import {useEffect,useState,use} from 'react';
import Link from 'next/link';
import {Button,Modal,toast} from '@/components/ui';
import {readJson,useWorkflowMutation,fieldClass,statusLabels} from '@/components/production/client';
import {OrderDraft} from '@/components/production/OrderDraft';
import {StockDocuments} from '@/components/production/StockDocuments';
import {PhotosField} from '@/components/production/PhotosField';
import {requiredQcChecks} from '@/lib/production/bom';
const checkNames:any={dimensions:'Kích thước / dấu chữ',appearance:'Bề mặt / màu sắc',structure:'Khung / liên kết',accessories:'Phụ kiện / đóng gói',electrical:'An toàn điện',lightUniformity:'Độ đều ánh sáng'};
export default function ProductionDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[o,setOrder]=useState<any>(null),[meta,setMeta]=useState<any>(null),[error,setError]=useState(''),[tab,setTab]=useState('steps'),[edit,setEdit]=useState(false),[form,setForm]=useState<any>(null),[photoBusy,setPhotoBusy]=useState(false);
 useSetPageHeader({title:"Sản xuất",subtitle:"Chi tiết lệnh",screenCode:"M13.1"},[]);
 const {busy,mutate,run}=useWorkflowMutation();
 async function load(){try{const [d,m]=await Promise.all([readJson(`/api/production-orders/${id}`),readJson('/api/production-orders/metadata')]);setOrder(d.order);setMeta(m);setError('');}catch(e:any){setError(e.message);}}
 useEffect(()=>{void load();},[id]);
 const action=async(body:any)=>{await mutate(`/api/production-orders/${id}/actions`,body);setForm(null);toast.success('Đã lưu');await load();};
 if(error)return <div className="p-4 text-sm text-red-600" role="alert">{error}<Button onClick={()=>load()}>Tải lại</Button></div>;
 if(!o || !meta)return <p className="p-4 text-xs">Đang tải hồ sơ sản xuất…</p>;
 const caps=meta.capabilities,line=o.lines.find((l:any)=>l.id===form?.lineId),change=(v:any)=>setForm((f:any)=>({...f,...v}));
 return <div className="p-3 text-xs space-y-3">
  <div className="flex justify-between flex-wrap gap-2"><div><Link href="/san-xuat" className="text-blue-600">Sản xuất</Link> / {o.code}<h1 className="text-lg font-semibold">{o.title}</h1><span className="text-slate-500">{statusLabels[o.status]} · Hạn: {o.due_at?new Date(o.due_at).toLocaleString('vi-VN'):'Chưa đặt'}</span></div><div className="flex gap-2 items-start"><Button size="sm" variant="secondary" onClick={()=>load()}>Làm mới</Button>{o.status==='draft' && !o.documents.length && caps['production_order.update'] && <Button size="sm" variant="secondary" onClick={()=>setEdit(true)}>Sửa lệnh nháp</Button>}{o.status==='draft' && !o.documents.length && caps['production_order.release'] && <Button size="sm" disabled={busy} onClick={()=>run(()=>action({action:'submit'}))}>Gửi duyệt / Tạo phiếu NVL</Button>}{caps['production_order.update'] && !o.documents.some((d:any)=>['completed','reversed'].includes(d.status)) && !o.lines.some((l:any)=>l.reports.length) && o.status!=='cancelled' && <Button size="sm" variant="secondary" disabled={busy} onClick={()=>run(()=>action({action:'cancel'}))}>Hủy lệnh</Button>}{caps['sales_order.read'] && <Link className="text-blue-600 p-2" href={`/ban-hang/theo-san-xuat?projectId=${o.project_id}&productionOrderId=${id}`}>Bán thành phẩm</Link>}</div></div>
  <div className="flex gap-2 border-b">{[['steps','Hạng mục & Công đoạn'],['materials','NVL & Phiếu kho'],['qc','QC & Nhập thành phẩm'],['files','Hồ sơ đã chốt']].map(([k,t])=><button key={k} className={`p-2 border-b-2 ${tab===k?'text-blue-600 border-blue-600':'border-transparent'}`} onClick={()=>setTab(k)}>{t}</button>)}</div>
  {tab==='steps' && o.lines.map((l:any)=><section key={l.id} className="border rounded p-3 space-y-2"><div className="flex justify-between"><strong>{l.title} · {l.item_code}</strong><span>{statusLabels[l.status]} · Đã nhập {Number(l.received_qty)}/{Number(l.target_qty)} {l.unit_name}</span></div><p className="text-slate-500">Nhóm: {l.team_name} · BOM phiên bản {l.snapshot.bom.revision_no} · Hạng mục {l.id}</p><table className="w-full"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Công đoạn</th><th>Tiến độ</th><th>Bắt đầu / Hoàn thành</th><th></th></tr></thead><tbody>{l.steps.map((s:any,n:number)=><tr key={s.id} className="border-t"><td className="p-2">{n+1}. {s.title}</td><td className="text-center">{s.progress}% · {statusLabels[s.status]}</td><td className="text-center">{s.started_at?new Date(s.started_at).toLocaleString('vi-VN'):'—'} / {s.completed_at?new Date(s.completed_at).toLocaleString('vi-VN'):'—'}</td><td className="p-1">{n<l.steps.length-1 && caps['production_order.report'] && ['ready','in_progress','rework'].includes(l.status) && <Button size="sm" variant="secondary" onClick={()=>setForm({action:'report',lineId:l.id,stepId:s.id,progress:Number(s.progress),outputQty:0,wasteQty:0,notes:'',photosText:'',materials:l.materials.map((m:any)=>({itemId:m.item_id,qty:0}))})}>Ghi công đoạn</Button>}</td></tr>)}</tbody></table><details><summary className="cursor-pointer text-blue-600">Nhật ký ({l.reports.length})</summary>{l.reports.map((r:any)=><div key={r.id} className="border-b p-2">{new Date(r.reported_at).toLocaleString('vi-VN')} · {l.steps.find((s:any)=>s.id===r.step_id)?.title} · {r.progress}% · Sản lượng {r.output_qty} / Hao hụt {r.waste_qty}<p>{r.notes}</p><p className="text-slate-500">Người ghi: {r.reported_by}</p>{r.materials?.filter((m:any)=>Number(m.qty)>0).map((m:any)=><span key={m.itemId} className="mr-3">{l.materials.find((v:any)=>v.item_id===m.itemId)?.name}: {m.qty}</span>)}{r.photos?.map((url:string)=><a key={url} href={url} target="_blank" rel="noreferrer" className="text-blue-600 mr-2">Ảnh</a>)}</div>)}</details></section>)}
  {tab==='materials' && <><p className="text-slate-500">Duyệt giữ vật tư; xác nhận xuất thực tế mới giảm tồn và cho phép bắt đầu.</p>{o.lines.map((l:any)=><section key={l.id} className="border rounded p-2"><strong>{l.title}</strong><table className="w-full"><thead className="bg-slate-50"><tr>{['NVL','Cần','Đơn vị cơ sở','Kho cấp','Chứng từ bổ sung / trả dư'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{l.materials.map((m:any)=><tr key={m.id} className="border-t"><td className="p-2">{m.code} · {m.name}</td><td>{Number(m.required_base_qty)}</td><td>{m.unit_name}</td><td>{m.warehouse_name}</td><td className="flex gap-1 p-1">{caps['production_order.update'] && ['released','in_progress','completed'].includes(o.status) && ['supplement','return'].map(a=><Button key={a} size="sm" variant="secondary" onClick={()=>setForm({action:a,lineId:l.id,materialId:m.id,warehouseId:m.source_warehouse_id,lotId:'',qty:0,notes:''})}>{a==='return'?'Trả dư':'Cấp bổ sung'}</Button>)}</td></tr>)}</tbody></table></section>)}<StockDocuments documents={o.documents} capabilities={caps} onChanged={load}/></>}
  {tab==='qc' && <>{o.lines.map((l:any)=><section key={l.id} className="border rounded p-3 space-y-2"><div className="flex justify-between"><strong>{l.title} · Đã nhập {Number(l.received_qty)}/{Number(l.target_qty)} {l.unit_name}</strong>{caps['production_order.qc'] && ['in_progress','rework'].includes(l.status) && <Button size="sm" onClick={()=>setForm({action:'qc',lineId:l.id,acceptedQty:0,rejectedQty:0,checks:{},defectNotes:'',destinationWarehouseId:'',unitCost:0,photosText:''})}>QC đợt hoàn thành</Button>}</div>{l.qc.map((q:any)=><div key={q.id} className="p-2 bg-slate-50">{q.code} · Đạt {Number(q.accepted_qty)} / Lỗi {Number(q.rejected_qty)} · {q.defect_notes}<p className="text-slate-500">{Object.entries(q.checks || {}).map(([k,v])=>`${checkNames[k] || k}: ${v?'Đạt':'Lỗi'}`).join(' · ')}</p></div>)}<table className="w-full"><thead><tr>{['Lô riêng','Đạt','Phiếu nhập','Trạng thái'].map(t=><th key={t} className="text-left p-1">{t}</th>)}</tr></thead><tbody>{l.outputs.map((v:any)=><tr key={v.id} className="border-t"><td className="p-1">{v.lot_code}</td><td>{Number(v.accepted_qty)}</td><td>{v.receipt_code}</td><td>{statusLabels[v.receipt_status]}</td></tr>)}</tbody></table></section>)}<StockDocuments documents={o.documents.filter((d:any)=>d.workflow_kind==='production_output' || d.workflow_kind==='reversal')} capabilities={caps} onChanged={load}/></>}
  {tab==='files' && <><Link className="text-blue-600" href={`/du-an/${o.project_id}`}>Mở dự án / WBS</Link>{o.lines.map((l:any)=>{const source=l.snapshot.design,proof=source?.proof,survey=source?.survey;return <section key={l.id} className="border rounded p-3 space-y-2"><strong>{l.title} · BOM {l.snapshot.bom.code} phiên bản {l.snapshot.bom.revision_no}</strong><p>Maket {proof?.code} · Khảo sát {survey?.code} · {l.snapshot.bom.width_meters} × {l.snapshot.bom.height_meters} m</p>{proof?.file_url && <a href={proof.file_url} target="_blank" rel="noreferrer" className="text-blue-600">Maket / bản vẽ dim đã chốt</a>}<details><summary className="cursor-pointer">Thông số khảo sát và thiết kế chốt</summary><pre className="p-2 bg-slate-50 whitespace-pre-wrap break-all max-h-96 overflow-auto">{JSON.stringify(source,null,2)}</pre></details><table className="w-full"><tbody>{l.snapshot.bom.lines.map((b:any)=><tr key={b.id} className="border-b"><td className="p-1">{b.description}</td><td>{b.item_code} · {b.item_name}</td><td>{b.quantity} {b.unit_name} + {b.waste_rate}%</td></tr>)}</tbody></table></section>;})}</>}
  <Modal isOpen={edit} onClose={()=>setEdit(false)} title="Sửa lệnh nháp" maxWidth="6xl">{edit && <OrderDraft meta={meta} projectId={o.project_id} order={o} onSaved={()=>{setEdit(false);void load();}}/>}</Modal>
  <Modal isOpen={Boolean(form)} onClose={()=>{if(!photoBusy)setForm(null);}} title={form?.action==='report'?'Ghi nhận công đoạn':form?.action==='qc'?'Kiểm tra QC thực tế':form?.action==='return'?'Trả vật tư dư':'Cấp vật tư bổ sung'} maxWidth="2xl">{form && <div className="space-y-3 text-xs"><strong>{line?.title}</strong>{form.action==='report' && <><div className="grid grid-cols-3 gap-2">{[['progress','Tiến độ %'],['outputQty','Sản lượng công đoạn'],['wasteQty','Hao hụt']].map(([k,t])=><label key={k}>{t}<input className={fieldClass} type="number" min="0" max={k==='progress'?100:undefined} step="any" value={form[k]} onChange={e=>change({[k]:Number(e.target.value)})}/></label>)}</div><p>Vật tư thực dùng trong lần ghi này (đơn vị cơ sở)</p>{form.materials.map((m:any,n:number)=><label key={m.itemId} className="flex gap-2 items-center">{line.materials.find((v:any)=>v.item_id===m.itemId)?.name}<input className={`${fieldClass} max-w-32`} type="number" min="0" step="any" value={m.qty} onChange={e=>change({materials:form.materials.map((v:any,i:number)=>i===n?{...v,qty:Number(e.target.value)}:v)})}/></label>)}<label>Ghi chú<textarea className={`${fieldClass} h-20`} value={form.notes} onChange={e=>change({notes:e.target.value})}/></label></>}
  {form.action==='qc' && <><div className="grid grid-cols-2 gap-2">{[['acceptedQty','Lượng đạt'],['rejectedQty','Lượng lỗi'],['unitCost','Giá thành / đơn vị'],['agingTestHours','Giờ chạy thử']].filter(([k])=>k!=='agingTestHours'||line.has_electrical).map(([k,t])=><label key={k}>{t}<input className={fieldClass} type="number" min="0" step="any" value={form[k] || 0} onChange={e=>change({[k]:Number(e.target.value)})}/></label>)}</div>{requiredQcChecks(line.has_electrical).map(k=><label key={k} className="flex items-center justify-between">{checkNames[k]}<select aria-label={checkNames[k]} className={`${fieldClass} max-w-48`} value={typeof form.checks[k]==='boolean'?String(form.checks[k]):''} onChange={e=>change({checks:{...form.checks,[k]:e.target.value===''?undefined:e.target.value==='true'}})}><option value="">Chưa xác nhận</option><option value="true">Đạt</option><option value="false">Lỗi</option></select></label>)}<label>Kho nhập thành phẩm<select aria-label="Kho nhập thành phẩm" className={fieldClass} value={form.destinationWarehouseId} onChange={e=>change({destinationWarehouseId:e.target.value})}><option value="">Chọn kho</option>{meta.warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Mô tả lỗi / hướng sửa<textarea className={`${fieldClass} h-20`} value={form.defectNotes} onChange={e=>change({defectNotes:e.target.value})}/></label></>}
  {['supplement','return'].includes(form.action) && <><label>Số lượng ({line?.materials.find((m:any)=>m.id===form.materialId)?.unit_name})<input className={fieldClass} type="number" min="0.000001" step="any" value={form.qty} onChange={e=>change({qty:Number(e.target.value)})}/></label><label>Kho<select className={fieldClass} value={form.warehouseId} onChange={e=>change({warehouseId:e.target.value})}>{meta.warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{form.action==='return' && <label>Lô đã cấp<select className={fieldClass} value={form.lotId} onChange={e=>change({lotId:e.target.value})}><option value="">Chọn lô đã xuất</option>{line?.issuedLots?.filter((l:any)=>l.production_material_id===form.materialId).map((l:any)=><option key={l.lot_id} value={l.lot_id}>{l.lot_code} · Còn tại xưởng tối đa {l.net_issued}</option>)}</select></label>}</>}
  {['report','qc'].includes(form.action) && <PhotosField value={form.photosText} onChange={v=>change({photosText:v})} onBusyChange={setPhotoBusy}/>}<div className="flex justify-end"><Button disabled={busy || photoBusy} onClick={()=>run(async()=>{const {photosText,...body}=form;await action({...body,photos:photosText?.split('\n').map((s:string)=>s.trim()).filter(Boolean)});})}>Lưu{form.action==='qc'?' / Tạo phiếu nhập chờ duyệt':''}</Button></div></div>}</Modal>
 </div>;
}
