import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {projectId,surveys} from './fixtures/maquette-surveys.mjs';
const browser=await chromium.launch({headless:true});
try {
  const page=await browser.newPage({viewport:{width:1600,height:1100},storageState:'tests/e2e/state-admin.json'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(`**/api/surveys?projectId=${projectId}`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({surveys:[...surveys,{...surveys[0],id:'foreign-survey',code:'KS-OTHER',projectId:'other-project'}]})}));
  const url=`http://localhost:3000/du-an/${projectId}/thiet-ke-quy-chuan`;
  await page.goto(url,{waitUntil:'domcontentloaded'});
  const selector=page.getByRole('combobox',{name:'Phiếu khảo sát của dự án'});
  await selector.waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-label="Phiếu khảo sát của dự án"]').disabled);
  assert.equal(await selector.locator('option').count(),4);
  assert.equal(await selector.locator('option[value^="preset-"]').count(),0);
  assert.equal(await selector.locator('option[value="foreign-survey"]').count(),0);
  assert.equal(await page.getByRole('textbox',{name:'Tên đại lý',exact:true}).inputValue(),'');
  assert.equal(await page.locator('svg[data-ready=true]').count(),0,'No fabricated drawing before selecting a survey');
  await selector.selectOption('survey-horizontal');
  await page.locator('svg[data-ready=true]').waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Tên đại lý',exact:true}).inputValue(),surveys[0].metadata.dealerName);
  assert.equal(await page.getByPlaceholder('0962 464 230').inputValue(),surveys[0].metadata.dealerPhone);
  assert.equal(await page.getByPlaceholder('Số nhà, đường, phường, quận/huyện, tỉnh...').inputValue(),surveys[0].metadata.dealerAddress);
  await selector.selectOption('survey-pillar');
  assert.equal(await page.getByPlaceholder('0962 464 230').inputValue(),'','Do not keep the previous survey phone');
  assert.equal(await page.getByPlaceholder('Số nhà, đường, phường, quận/huyện, tỉnh...').inputValue(),'');
  assert.equal(await page.locator('[data-auto-layout]').getAttribute('data-auto-layout'),'LAYOUT_09_PILLAR');
  let payload;
  await page.route('**/api/design-proofs',async route=>{
    if(route.request().method()!=='POST')return route.continue();
    payload=route.request().postDataJSON();await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({proof:{id:'test-proof',title:payload.title,status:payload.status}})});
  });
  await page.getByRole('button',{name:'1-Click Lưu Dự Án 360'}).click();
  await page.getByRole('button',{name:'Cập Nhật Bản Vẽ Này'}).waitFor();
  assert.equal(payload.projectId,projectId);
  assert.equal(JSON.parse(payload.clientFeedback)._parametricSpec.surveyId,'survey-pillar');
  // The survey ID, not stale URL dimensions/text, is authoritative.
  await page.goto(`${url}?surveyId=survey-narrow&w=99&h=99&title=Wrong&addr=Wrong`,{waitUntil:'domcontentloaded'});
  await page.locator('svg[data-ready=true]').waitFor();
  assert.equal(await page.locator('input[type=number]').nth(0).inputValue(),'5.9');
  assert.equal(await page.locator('input[type=number]').nth(1).inputValue(),'0.9');
  assert.equal(await page.getByRole('textbox',{name:'Tên đại lý',exact:true}).inputValue(),'NAM LONG PHÁT');
  await page.goto(`${url}?surveyId=foreign-survey`,{waitUntil:'domcontentloaded'});
  await page.getByRole('alert').filter({hasText:'không thuộc dự án'}).waitFor();
  assert.equal(await page.locator('svg[data-ready=true]').count(),0);
  await page.route('**/api/surveys/survey-narrow',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({survey:surveys[2]})}));
  await page.goto('http://localhost:3000/du-an/thiet-ke-quy-chuan?surveyId=survey-narrow',{waitUntil:'domcontentloaded'});
  await page.locator('svg[data-ready=true]').waitFor();
  assert.equal(await selector.locator('option').count(),4,'A direct survey link must list only its project surveys');
  assert.equal(await selector.inputValue(),'survey-narrow');
  await page.goto('http://localhost:3000/du-an/thiet-ke-quy-chuan',{waitUntil:'domcontentloaded'});
  await page.getByText('Mở thiết kế từ dự án hoặc một phiếu khảo sát để nạp dữ liệu.',{exact:true}).waitFor();
  assert.equal(await page.locator('svg[data-ready=true]').count(),0);
  await page.route('**/api/surveys?projectId=empty-project',route=>route.fulfill({status:200,contentType:'application/json',body:'{"surveys":[]}'}));
  await page.goto('http://localhost:3000/du-an/empty-project/thiet-ke-quy-chuan',{waitUntil:'domcontentloaded'});
  await page.getByText('Dự án chưa có phiếu khảo sát.',{exact:true}).waitFor();
  assert.equal(await page.locator('svg[data-ready=true]').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS: project-only survey options, real fields/dimensions, missing data cleared, saved survey link, cross-project rejection and empty project state');
} finally {await browser.close();}
