const assert=require('assert/strict');
const {productionDb}=require('./helpers/production-db.cjs');
const {fixture}=require('./helpers/production-fixture.cjs');
(async()=>{const db=await productionDb();try{
 const f=await fixture(db),ctx=db.ctx,{ProductionService:P}=db.load('src/services/production.service.ts'),{ProductionBomService:B}=db.load('src/services/production-bom.service.ts'),{InventoryService:I}=db.load('src/services/inventory.service.ts');
 const from=await B.fromDesign(ctx,{requestId:f.request(),projectId:f.project,designProofId:f.proof});
 const fresh=await B.detail(ctx,from.bomId);assert.equal(Number(fresh.width_meters),12);assert.equal(Number(fresh.height_meters),2.4);assert.equal(fresh.lines.length,3,'No guessed lights/accessories');assert.equal(fresh.needsMapping,true);
 const variant=await B.createRepresentative(ctx,{requestId:f.request(),code:'frame',name:'Khung bộ 40x40',specificationKey:'40x40',quantityBasis:'count'});
 await B.saveRepresentative(ctx,variant.representative.id,{defaultItemId:f.product,defaultUnitId:f.unit,quantityBasis:'count',rules:{coefficient:1,wasteRate:0}});
 await db.query('UPDATE erp.site_surveys SET metadata=$1 WHERE id=$2',[{ironBoxType:'40x40',signMaterial:'Bạt đã khảo sát'},f.survey]);
 const specific=await B.fromDesign(ctx,{requestId:f.request(),projectId:f.project,designProofId:f.proof}),specificBom=await B.detail(ctx,specific.bomId);
 assert.equal(Number(specificBom.lines[0].quantity),1,'Count representative does not take perimeter as piece count');assert.equal(specificBom.lines[0].item_id,f.product);assert.match(specificBom.lines[1].description,/Bạt đã khảo sát/);
 await assert.rejects(B.fromDesign(ctx,{requestId:f.request(),projectId:f.project2,designProofId:f.proof}),/đúng dự án/);
 await assert.rejects(B.fromDesign(ctx,{requestId:f.request(),projectId:f.project,designProofId:f.proof,surveyId:f.project2}),/không khớp/);
 const legacy=(await db.query("INSERT INTO erp.project_boms(organization_id,code,title,project_id) VALUES($1,'LEGACY','BOM cũ',$2) RETURNING id",[ctx.orgId,f.project])).rows[0].id;
 await B.save(ctx,legacy,{requestId:f.request(),designProofId:f.proof,lines:[{representativeId:f.rep,description:'Khung đã kiểm tra',itemId:f.raw,unitId:f.rawUnit,quantity:4,wasteRate:0}]});
 const upgraded=await B.detail(ctx,legacy);assert.equal(upgraded.needsMapping,false);assert.equal(Number(upgraded.width_meters),12);assert.equal(upgraded.design_proof_id,f.proof);
 await db.query('UPDATE erp.project_boms SET notes=$1 WHERE id=$2',['Kiểm tra xương bổ sung',f.bom]);
 const revised=await B.revise(ctx,f.bom,{requestId:f.request()});assert.notEqual(revised.bomId,f.bom);assert.equal((await B.detail(ctx,revised.bomId)).notes,'Kiểm tra xương bổ sung');
 const input={requestId:f.request(),projectId:f.project,sourceWarehouseId:f.warehouse,lines:[{bomId:f.bom,outputItemId:f.product,unitId:f.unit,teamId:f.team,targetQty:1},{bomId:revised.bomId,outputItemId:f.product,unitId:f.unit,teamId:f.team,targetQty:3}]};
 const [a,b]=await Promise.all([P.create(ctx,input),P.create(ctx,input)]);assert.equal(a.orderId,b.orderId,'Concurrent duplicate request creates one order');
 let o=await P.detail(ctx,a.orderId);assert.equal(o.lines.length,2);assert.equal(o.target_qty,null,'Header does not aggregate outputs');
 const sub=await P.submit(ctx,a.orderId,{requestId:f.request()});assert.equal(sub.documentIds.length,1);const doc=sub.documentIds[0];
 await assert.rejects(B.save(ctx,f.bom,{requestId:f.request(),lines:[]}),/đã chốt/);
 await assert.rejects(db.query("UPDATE erp.project_boms SET title='Old endpoint changed title' WHERE id=$1",[f.bom]),/BOM da chot/);
 await Promise.all([I.approveDocument(doc,ctx.userId),I.approveDocument(doc,ctx.userId)]);assert.equal(Number((await db.query('SELECT reserved_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].reserved_qty),20);
 await I.completeDocument(doc,ctx.userId);o=await P.detail(ctx,a.orderId);assert.equal(o.lines.every(l=>l.status==='ready'),true);
 const l=o.lines.find(l=>Number(l.target_qty)===1),m=l.materials[0];
 const extra=await P.materialDocument(ctx,a.orderId,{requestId:f.request(),lineId:l.id,materialId:m.id,warehouseId:f.warehouse,qty:2},false);await I.approveDocument(extra.documentId,ctx.userId);await I.completeDocument(extra.documentId,ctx.userId);
 await P.report(ctx,a.orderId,{requestId:f.request(),lineId:l.id,stepId:l.steps[0].id,progress:100,materials:[{itemId:f.raw,qty:4}]});
 await assert.rejects(P.report(ctx,a.orderId,{requestId:f.request(),lineId:l.id,stepId:l.steps[1].id,progress:100,materials:[{itemId:f.raw,qty:10}]}),/vượt lượng/);
 const ret=await P.materialDocument(ctx,a.orderId,{requestId:f.request(),lineId:l.id,materialId:m.id,warehouseId:f.warehouse,lotId:f.lot,qty:2},true);
 await assert.rejects(P.materialDocument(ctx,a.orderId,{requestId:f.request(),lineId:l.id,materialId:m.id,warehouseId:f.warehouse,lotId:f.lot,qty:2},true),/vượt vật tư/);
 await I.approveDocument(ret.documentId,ctx.userId);await I.completeDocument(ret.documentId,ctx.userId);assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].on_hand_qty),80);
 await assert.rejects(P.report(ctx,a.orderId,{requestId:f.request(),lineId:l.id,stepId:l.steps.at(-1).id,progress:100}),/QC thực tế/);
 const {assertProject,assertWarehouse}=db.load('src/lib/production/context.ts');
 const own={...ctx,userId:'other',membershipId:f.project2,employeeId:null,capabilities:{...ctx.capabilities,'production_order.read':{isEnabled:true,scope:'OWN'}}};
 await assert.rejects(assertProject(db.pool,own,f.project,'production_order.read'),/ngoài phạm vi/);
 const scoped={...ctx,capabilities:{...ctx.capabilities,'stock_document.read':{isEnabled:true,scope:'ASSIGNED'}}};
 await assert.rejects(assertWarehouse(db.pool,scoped,f.warehouse,'stock_document.read'),/ngoài phạm vi/);
 const selectedScope={...ctx,capabilities:{...ctx.capabilities,'production_order.report':{isEnabled:true,scope:'SELECTED'}}};
 await assert.rejects(assertProject(db.pool,selectedScope,f.project,'production_order.report'),/ngoài phạm vi/);
 await assert.rejects(P.create(ctx,{...input,lines:input.lines.slice(0,1)}),/nội dung khác/);
 const ordinary=await I.createDocument({type:'receipt',destinationWarehouseId:f.warehouse,purpose:'Normal receipt',submitNow:true,lines:[{itemId:f.raw,lotId:f.lot,unitId:f.rawUnit,qty:1}]},ctx.userId);await I.approveDocument(ordinary,ctx.userId);await I.completeDocument(ordinary,ctx.userId);
 assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].on_hand_qty),81,'Ordinary stock workflow preserved');
 console.log('PASS: exact survey/maket, missing mappings, frozen BOM, multi-item order, concurrent retries, supplementary issues, used-material limits, excess returns, QC gate and scope denial');
}finally{await db.close();}})().catch(e=>{console.error(e.message,e.detail || '',e.stack);process.exitCode=1;});
