const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const exportsObject={};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/production/bom.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exportsObject});
const {expandMappedBom,requiredQcChecks,validatePhotos}=exportsObject;
const raw={id:'raw',code:'RAW',name:'Sắt',kind:'material',baseUnitId:'m',isActive:true,conversions:[{unitId:'bar',factor:6}]};
const bought={id:'bought',code:'BUY',name:'Phụ kiện',kind:'product',baseUnitId:'piece',isActive:true,conversions:[]};
const semi={id:'semi',code:'SEMI',name:'Khung',kind:'semi_finished',baseUnitId:'piece',isActive:true,conversions:[],bom:[{itemId:'raw',unitId:'bar',quantity:2}]};
const product={id:'product',code:'TP',name:'Biển',kind:'product',baseUnitId:'piece',isActive:true,conversions:[],bom:[{itemId:'semi',unitId:'piece',quantity:2},{itemId:'bought',unitId:'piece',quantity:3}]};
const catalog=[raw,bought,semi,product];
const line=(itemId,unitId,quantity=1,wasteRate=0)=>({id:'line',representativeId:'frame',description:'Khung',itemId,unitId,quantity,wasteRate});
const r=expandMappedBom([line('product','piece'),line('raw','m',2)],catalog,2);
assert.equal(r.find(m=>m.itemId==='raw').baseQty,52);
assert.equal(r.find(m=>m.itemId==='bought').baseQty,6);
assert.equal(r.find(m=>m.itemId==='raw').paths.length,2);
assert.equal(expandMappedBom([line('raw','bar',1,10)],catalog)[0].baseQty,6.6);
assert.throws(()=>expandMappedBom([line('raw','missing')],catalog),/quy đổi/);
assert.throws(()=>expandMappedBom([line(undefined,'m')],catalog),/Chưa gán/);
assert.throws(()=>expandMappedBom([line('raw','m',0)],catalog),/lớn hơn/);
assert.throws(()=>expandMappedBom([line('raw','m',1,101)],catalog),/Hao hụt/);
const cycle={...semi,bom:[{itemId:'product',unitId:'piece',quantity:1}]};
assert.throws(()=>expandMappedBom([line('product','piece')],[raw,bought,cycle,product]),/vòng lặp/);
assert.throws(()=>expandMappedBom([line('raw','m')],[{...raw,isActive:false}]),/hợp lệ/);
assert.throws(()=>expandMappedBom([line('bought','piece')],[{...bought,bom:{broken:true}}]),/BOM cấu thành/);
assert.throws(()=>expandMappedBom([line('bought','piece')],[{...bought,bom:[null]}]),/BOM cấu thành/);
assert.equal(requiredQcChecks(false).includes('electrical'),false);
assert.equal(requiredQcChecks(true).includes('electrical'),true);
assert.doesNotThrow(()=>validatePhotos(['data:image/jpeg;base64,AA==']));
assert.throws(()=>validatePhotos(['javascript:alert(1)']),/Ảnh/);
assert.throws(()=>validatePhotos(['data:image/svg+xml;base64,AA==']),/Ảnh/);
console.log('PASS: direct material, bought product, recursive BOM, aggregation, units, waste, missing mappings, cycles and applicable QC');
