const assert=require('assert/strict');const {productionDb}=require('./helpers/production-db.cjs');const {fixture}=require('./helpers/production-fixture.cjs');
(async()=>{const db=await productionDb();try{
 const f=await fixture(db),ctx=db.ctx;
 const {ProductionService:P}=db.load('src/services/production.service.ts'),{ProductionSalesService:S}=db.load('src/services/production-sales.service.ts'),{InventoryService:I}=db.load('src/services/inventory.service.ts');
 const input={requestId:f.request(),projectId:f.project,sourceWarehouseId:f.warehouse,lines:[{bomId:f.bom,outputItemId:f.product,unitId:f.unit,teamId:f.team,targetQty:2}]};
 const created=await P.create(ctx,input);assert.equal((await P.create(ctx,input)).orderId,created.orderId);
 const id=created.orderId;const submitted=await P.submit(ctx,id,{requestId:f.request()});
 await assert.rejects(P.report(ctx,id,{requestId:f.request(),lineId:'missing',stepId:'missing',progress:100}),/chưa sẵn sàng/);
 const issue=submitted.documentIds[0];await I.approveDocument(issue,ctx.userId);
 await I.approveDocument(issue,ctx.userId);
 assert.equal(Number((await db.query('SELECT reserved_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].reserved_qty),10);
 assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].on_hand_qty),100);
 let order=await P.detail(ctx,id),line=order.lines[0];assert.equal(line.status,'waiting_materials');
 await assert.rejects(P.report(ctx,id,{requestId:f.request(),lineId:line.id,stepId:line.steps[0].id,progress:100}),/chưa được cấp đủ/);
 await I.completeDocument(issue,ctx.userId);
 await I.completeDocument(issue,ctx.userId);
 assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE item_id=$1',[f.raw])).rows[0].on_hand_qty),90);
 order=await P.detail(ctx,id);line=order.lines[0];assert.equal(line.status,'ready');
 for(const step of line.steps.slice(0,-1))await P.report(ctx,id,{requestId:f.request(),lineId:line.id,stepId:step.id,progress:100,outputQty:2});
 await assert.rejects(P.qc(ctx,id,{requestId:f.request(),lineId:line.id,acceptedQty:1,rejectedQty:0,checks:{}}),/tiêu chí/);
 const checks={dimensions:true,appearance:true,structure:true,accessories:true};
 const qcInput={requestId:f.request(),lineId:line.id,acceptedQty:1,rejectedQty:1,checks,defectNotes:'Sửa bề mặt',destinationWarehouseId:f.outputWarehouse};
 const first=await P.qc(ctx,id,qcInput);assert.equal((await P.qc(ctx,id,qcInput)).lotId,first.lotId);
 assert.equal((await P.detail(ctx,id)).lines[0].status,'rework');
 assert.equal((await S.available(ctx,f.project)).length,0,'Pending receipt is not saleable');
 await I.approveDocument(first.receiptId,ctx.userId);await I.completeDocument(first.receiptId,ctx.userId);
 line=(await P.detail(ctx,id)).lines[0];assert.equal(Number(line.received_qty),1);
 for(const step of line.steps.slice(0,-1).filter(s=>s.status!=='done'))await P.report(ctx,id,{requestId:f.request(),lineId:line.id,stepId:step.id,progress:100,outputQty:1});
 const second=await P.qc(ctx,id,{requestId:f.request(),lineId:line.id,acceptedQty:1,rejectedQty:0,checks,destinationWarehouseId:f.outputWarehouse});assert.notEqual(second.lotId,first.lotId);
 await I.approveDocument(second.receiptId,ctx.userId);await I.completeDocument(second.receiptId,ctx.userId);
 assert.equal((await P.detail(ctx,id)).status,'completed');
 const products=await S.available(ctx,f.project);assert.equal(products.length,2);
 const saleInput={requestId:f.request(),projectId:f.project,customerId:f.customer,recordReceivable:true,lines:[{itemId:f.product,lotId:first.lotId,warehouseId:f.outputWarehouse,unitId:f.unit,qty:1,unitPrice:100}]};
 await assert.rejects(S.create(ctx,{...saleInput,requestId:f.request(),projectId:f.project2}),/đúng lô/);
 const sale=await S.create(ctx,saleInput);assert.equal((await S.create(ctx,saleInput)).orderId,sale.orderId);
 const competing=await S.create(ctx,{...saleInput,requestId:f.request(),recordReceivable:false});
 const approved=await S.approve(ctx,sale.orderId,{requestId:f.request()});assert.equal(approved.documentIds.length,1);
 assert.equal(Number((await db.query('SELECT reserved_qty FROM erp.stock_balances WHERE lot_id=$1',[first.lotId])).rows[0].reserved_qty),1);
 await assert.rejects(S.approve(ctx,competing.orderId,{requestId:f.request()}),/Không đủ/);
 assert.equal((await db.query('SELECT count(*) AS n FROM erp.stock_documents WHERE sales_order_id=$1',[competing.orderId])).rows[0].n,0,'Failed approval rolls back all created documents');
 assert.equal((await S.approve(ctx,sale.orderId,{requestId:f.request()})).documentIds[0],approved.documentIds[0]);
 let doc=approved.documentIds[0];assert.equal((await db.query('SELECT status FROM erp.stock_documents WHERE id=$1',[doc])).rows[0].status,'submitted');
 await I.cancelDocument(doc,ctx.userId);assert.equal(Number((await db.query('SELECT reserved_qty FROM erp.stock_balances WHERE lot_id=$1',[first.lotId])).rows[0].reserved_qty),0);
 const replacement=await S.approve(ctx,sale.orderId,{requestId:f.request()});assert.notEqual(replacement.documentIds[0],doc);doc=replacement.documentIds[0];
 await I.approveDocument(doc,ctx.userId);await I.completeDocument(doc,ctx.userId);
 assert.equal((await S.detail(ctx,sale.orderId)).status,'completed');
 await S.approve(ctx,sale.orderId,{requestId:f.request()});assert.equal((await S.detail(ctx,sale.orderId)).status,'completed');
 assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE lot_id=$1',[first.lotId])).rows[0].on_hand_qty),0);
 assert.equal(Number((await db.query('SELECT count(*) AS n FROM erp.open_items WHERE sales_order_id=$1',[sale.orderId])).rows[0].n),1,'No duplicate receivable from stock creation/posting');
 const {ProductionStockService:R}=db.load('src/services/production-stock.service.ts');
 const returned=await R.reverse(ctx,doc,{requestId:f.request()});await I.approveDocument(returned.documentId,ctx.userId);await I.completeDocument(returned.documentId,ctx.userId);
 assert.equal(Number((await S.detail(ctx,sale.orderId)).lines[0].delivered_qty),0,'Return reverses delivered quantity');
 assert.equal(Number((await db.query('SELECT on_hand_qty FROM erp.stock_balances WHERE lot_id=$1',[first.lotId])).rows[0].on_hand_qty),1);
 const reversedOutput=await R.reverse(ctx,second.receiptId,{requestId:f.request()});await I.approveDocument(reversedOutput.documentId,ctx.userId);
 assert.equal(Number((await db.query('SELECT reserved_qty FROM erp.stock_balances WHERE lot_id=$1',[second.lotId])).rows[0].reserved_qty),1);
 await I.completeDocument(reversedOutput.documentId,ctx.userId);assert.equal(Number((await P.detail(ctx,id)).lines[0].received_qty),1);
 console.log('PASS: create/submit/approve/material posting, stage gates, partial QC, rework, unique output lots, pending receipts, exact-lot sales, competing reservations, rollback, duplicate requests and receivable preservation');
}finally{await db.close();}})().catch(e=>{console.error(e.message,e.detail||'',e.stack);process.exitCode=1;});
