/**
 * DANH MỤC QUYỀN VÀ MA TRẬN PHÂN QUYỀN MẪU BAN ĐẦU
 * Dựa trên tài liệu docs/MA_TRAN_PHAN_QUYEN_DONG.md (Mục 4, 5, 6)
 */

import { PermissionKey, ScopeKind, ResourceName, ActionName } from "@/types/iam";

export interface SeedGrant {
  roleCode: string;
  permission: PermissionKey;
  scope: ScopeKind;
  amountLimit?: number;
  currency?: string;
}

export const ROLE_DEFAULT_ROUTES: Record<string, string> = {
  SUPER_ADMIN: "/",
  ACCOUNTANT: "/tai-chinh",
  WAREHOUSE_KEEPER: "/kho",
  PROJECT_MANAGER: "/du-an",
  FIELD_WORKER: "/hien-truong",
  FLEET_OPERATOR: "/apps/doi-xe",
  FLEET_MANAGER: "/apps/doi-xe",
};

/**
 * Ma trận Role Grants mẫu ban đầu (Mục 5 docs/MA_TRAN_PHAN_QUYEN_DONG.md)
 */
export const SEED_ROLE_GRANTS: SeedGrant[] = [
  // --- ACCOUNTANT ---
  { roleCode: "ACCOUNTANT", permission: "customer.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "customer.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "customer.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "customer.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "supplier.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "supplier.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "supplier.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "supplier.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "quotation.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "quotation.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "sales_order.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "sales_order.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "sales_order.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "sales_order.submit", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "sales_order.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.submit", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.approve", scope: "ORG", amountLimit: 20000000, currency: "VND" },
  { roleCode: "ACCOUNTANT", permission: "purchase_order.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "item.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "item.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "item.cost_read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "inventory.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "inventory.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "stock_document.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "stock_document.approve", scope: "ORG", amountLimit: 50000000, currency: "VND" },
  { roleCode: "ACCOUNTANT", permission: "stock_document.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "stock_document.cost_read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "task.read", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "task.create", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "task.update", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "task.complete", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "work_report.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "work_report.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "project.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "project.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "contract.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "contract.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "production_order.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "acceptance.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "acceptance.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "field_event.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "trip.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "fleet_report.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "fleet.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.submit", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.post", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payment.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "receivable.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "receivable.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payable.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payable.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.approve", scope: "ORG", amountLimit: 5000000, currency: "VND" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.settle", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.create", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.update", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "expense_claim.submit", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "project_finance.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "project_finance.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.private_read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.private_update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "employee.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.create", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.approve", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.close", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "attendance.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "salary.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.generate", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.update", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.pay", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.export", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "payroll.ai_suggest", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "ai_run.read", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "ai_run.ocr", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "ai_run.speech", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "ai_run.ask", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "ai_run.retry", scope: "OWN" },
  { roleCode: "ACCOUNTANT", permission: "period_lock.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "period_lock.close", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "company_setting.read", scope: "ORG" },
  { roleCode: "ACCOUNTANT", permission: "company_setting.update", scope: "ORG" },

  // --- WAREHOUSE_KEEPER ---
  { roleCode: "WAREHOUSE_KEEPER", permission: "supplier.read", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "sales_order.read", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "purchase_order.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "purchase_order.create", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "purchase_order.update", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "purchase_order.submit", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "item.read", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "item.create", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "item.update", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "item.import", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "item.export", scope: "ORG" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "inventory.read", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "inventory.export", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "inventory.count", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.read", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.create", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.update", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.submit", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.post", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "stock_document.export", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "task.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "task.create", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "task.update", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "task.complete", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "work_report.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "work_report.create", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "work_report.update", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "work_report.submit", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "production_order.read", scope: "ASSIGNED" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "field_event.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "field_event.create", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "expense_claim.create", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "expense_claim.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "expense_claim.update", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "expense_claim.submit", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "employee.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "attendance.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "payroll.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "ai_run.read", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "ai_run.ocr", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "ai_run.speech", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "ai_run.ask", scope: "OWN" },
  { roleCode: "WAREHOUSE_KEEPER", permission: "ai_run.retry", scope: "OWN" },

  // --- PROJECT_MANAGER ---
  { roleCode: "PROJECT_MANAGER", permission: "customer.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "customer.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "customer.update", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "quotation.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "quotation.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "quotation.update", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "quotation.submit", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "quotation.export", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "sales_order.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "sales_order.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "sales_order.update", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "sales_order.submit", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "purchase_order.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "purchase_order.create", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "purchase_order.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "purchase_order.submit", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "item.read", scope: "ORG" },
  { roleCode: "PROJECT_MANAGER", permission: "stock_document.read", scope: "SELECTED" },
  { roleCode: "PROJECT_MANAGER", permission: "stock_document.create", scope: "SELECTED" },
  { roleCode: "PROJECT_MANAGER", permission: "stock_document.update", scope: "SELECTED" },
  { roleCode: "PROJECT_MANAGER", permission: "stock_document.submit", scope: "SELECTED" },
  { roleCode: "PROJECT_MANAGER", permission: "task.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "task.create", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "task.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "task.assign", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "task.complete", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.approve", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.export", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.update", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "work_report.submit", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "project.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "project.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "project.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "project.assign", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "project.close", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "project.export", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "contract.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "contract.create", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "contract.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "contract.export", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.create", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.release", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.complete", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.report", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "production_order.qc", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "project_template.read", scope: "ORG" },
  { roleCode: "PROJECT_MANAGER", permission: "project_template.create", scope: "ORG" },
  { roleCode: "PROJECT_MANAGER", permission: "project_template.update", scope: "ORG" },
  { roleCode: "PROJECT_MANAGER", permission: "project_template.archive", scope: "ORG" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.create", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.update", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.submit", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.approve", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "acceptance.export", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "field_event.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "field_event.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "trip.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "trip.attach", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "fleet_report.read", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "fleet.export", scope: "ASSIGNED" },
  { roleCode: "PROJECT_MANAGER", permission: "expense_claim.create", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "expense_claim.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "expense_claim.update", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "expense_claim.submit", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "employee.read", scope: "TEAM" },
  { roleCode: "PROJECT_MANAGER", permission: "attendance.read", scope: "TEAM" },
  { roleCode: "PROJECT_MANAGER", permission: "payroll.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "ai_run.read", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "ai_run.ocr", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "ai_run.speech", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "ai_run.ask", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "ai_run.retry", scope: "OWN" },
  { roleCode: "PROJECT_MANAGER", permission: "report_template.read", scope: "ORG" },

  // --- FIELD_WORKER ---
  { roleCode: "FIELD_WORKER", permission: "project.read", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "item.read", scope: "ORG" },
  { roleCode: "FIELD_WORKER", permission: "task.read", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "task.update", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "task.complete", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "task.create", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "work_report.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "work_report.create", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "work_report.update", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "work_report.submit", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "production_order.read", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "production_order.report", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "acceptance.read", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "acceptance.create", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "acceptance.update", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "acceptance.submit", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "field_event.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "field_event.create", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "trip.read", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "trip.complete", scope: "ASSIGNED" },
  { roleCode: "FIELD_WORKER", permission: "expense_claim.create", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "expense_claim.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "expense_claim.update", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "expense_claim.submit", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "employee.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "attendance.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "payroll.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "ai_run.read", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "ai_run.ocr", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "ai_run.speech", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "ai_run.ask", scope: "OWN" },
  { roleCode: "FIELD_WORKER", permission: "ai_run.retry", scope: "OWN" },

  // --- FLEET_OPERATOR ---
  { roleCode: "FLEET_OPERATOR", permission: "trip.read", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.create", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.update", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.assign", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.dispatch", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.complete", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.cancel", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "trip.attach", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "fleet.read", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "fleet.update", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "fleet.import", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "fleet.export", scope: "ORG" },
  { roleCode: "FLEET_OPERATOR", permission: "fleet_report.read", scope: "ORG" },

  // --- FLEET_MANAGER ---
  { roleCode: "FLEET_MANAGER", permission: "trip.read", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.create", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.update", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.assign", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.dispatch", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.complete", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.cancel", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "trip.attach", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet.read", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet.update", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet.import", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet.export", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_report.read", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_ot.approve", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_issue.close", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_setting.update", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_period.close", scope: "ORG" },
  { roleCode: "FLEET_MANAGER", permission: "fleet_period.reopen", scope: "ORG" },
];

/**
 * Điều kiện hiển thị / mở màn hình M00–M20 (Mục 6 docs/MA_TRAN_PHAN_QUYEN_DONG.md)
 */
export const SCREEN_REQUIREMENTS: Record<string, { permissions: PermissionKey[]; anyOf?: boolean; description: string }> = {
  M01: { permissions: [], description: "Bàn làm việc: yêu cầu membership active" },
  M02: { permissions: ["customer.read"], description: "Khách hàng" },
  M03: { permissions: ["quotation.read", "quotation.create"], anyOf: true, description: "Báo giá" },
  M04: { permissions: ["sales_order.read", "sales_order.create"], anyOf: true, description: "Bán hàng" },
  M05: { permissions: ["supplier.read"], description: "Nhà cung cấp" },
  M06: { permissions: ["purchase_order.read", "purchase_order.create"], anyOf: true, description: "Mua hàng" },
  M07: { permissions: ["item.read"], description: "Danh mục vật tư" },
  M08: { permissions: ["inventory.read", "warehouse.manage", "company_setting.update"], anyOf: true, description: "Danh sách kho và tồn kho" },
  M09: { permissions: ["stock_document.read", "stock_document.create"], anyOf: true, description: "Phiếu kho" },
  M10: { permissions: ["task.read"], description: "Trung tâm việc làm" },
  M11: { permissions: ["project.read", "project.create"], anyOf: true, description: "Dự án & Công trình" },
  M12: { permissions: ["project.read", "task.read"], anyOf: true, description: "Chi tiết dự án 360°" },
  M13: { permissions: ["project_template.read"], description: "Mẫu dự án" },
  "M13.1": { permissions: ["production_order.read"], description: "Sản xuất tại xưởng" },
  M14: { permissions: ["task.read", "field_event.create"], anyOf: true, description: "Hiện trường 1 chạm GPS" },
  M15: { permissions: ["fleet.read", "trip.read", "fleet_report.read"], anyOf: true, description: "Vận chuyển & Đội xe" },
  M16: { permissions: ["payment.read", "receivable.read", "payable.read", "cash_account.manage"], anyOf: true, description: "Tài chính & Sổ quỹ" },
  M17: { permissions: ["employee.read", "attendance.read"], anyOf: true, description: "Nhân sự & Chấm công" },
  M18: { permissions: ["payroll.read"], description: "Đánh giá lương AI" },
  M19: { permissions: ["ai_run.read", "ai_run.ask"], anyOf: true, description: "Trợ lý AI Signage" },
  M20: { permissions: ["role.read", "role.manage", "membership.read", "approval_policy.read", "company_setting.read"], anyOf: true, description: "Cài đặt & Phân quyền" },
  "M02.1": { permissions: ["customer.read"], description: "Khảo sát mặt bằng" },
  "M02.2": { permissions: ["project.read"], description: "Thiết kế chuẩn Nippon" },
  "M03.1": { permissions: ["quotation.create"], description: "Lập báo giá mới" },
  "M06.1": { permissions: ["purchase_order.create"], description: "Lập đơn mua hàng (PO)" },
  "M09.1": { permissions: ["stock_document.create"], description: "Lập phiếu kho mới" },
  "M16.1": { permissions: ["project.read", "stock_document.read", "payment.read"], anyOf: true, description: "Phân tích Điều hành Signage" },
  "M18.1": { permissions: ["salary.read"], description: "Chế độ lương & Quỹ phép" },
  APP_HRM: { permissions: ["employee.read", "attendance.read", "payroll.read", "salary.read"], anyOf: true, description: "App HRM - Quản trị Nhân sự & Lương" },
  APP_DOCS: { permissions: ["document.read", "document.manage", "project.read", "work_report.read"], anyOf: true, description: "Tài liệu nội bộ & Drive" },
  APP_FLEET: { permissions: ["fleet.read", "trip.read", "fleet_report.read"], anyOf: true, description: "App Đội Xe & Vận Chuyển (Fleet Pro)" },
};
