'use client';
import {useSetPageHeader} from '@/contexts/page-header-context';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button,Modal,toast} from '@/components/ui';
import {DataTable} from '@/components/shared';
import {BomEditor} from '@/components/production/BomEditor';
import {OrderDraft} from '@/components/production/OrderDraft';
import {readJson,useWorkflowMutation,fieldClass,statusLabels} from '@/components/production/client';
export default function ProductionPage(){
 const [meta,setMeta]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[project,setProject]=useState(''),[tab,setTab]=useState('orders'),[status,setStatus]=useState(''),[keyword,setKeyword]=useState(''),[error,setError]=useState(''),[editor,setEditor]=useState(''),[draft,setDraft]=useState(false),[createBom,setCreateBom]=useState(false),[proof,setProof]=useState(''),[repVariant,setRepVariant]=useState(false),[variant,setVariant]=useState<any>({code:'other',name:'',specificationKey:'',quantityBasis:'manual'});
 useSetPageHeader({title:"Sản xuất",subtitle:"Danh sách lệnh",screenCode:"M13.1"},[]);
 const {busy,mutate,run}=useWorkflowMutation();
 async function load(){try{const m=await readJson('/api/production-orders/metadata');setMeta(m);if(m.ready){setOrders((await readJson('/api/production-orders')).orders);setError('');}}catch(e:any){setError(e.message);}}
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setProject(p.get('projectId') || '');setTab(p.get('tab') || 'orders');setProof(p.get('designProofId') || '');setEditor(p.get('bomId') || '');void load();},[]);
 if(error)return <div className="p-4 text-sm"><p role="alert" className="text-red-600">{error}</p><Button onClick={()=>load()}>Tải lại</Button></div>;
 if(!meta)return <p className="p-4 text-xs">Đang tải sản xuất…</p>;
 if(!meta.ready)return <p className="p-4 text-sm">Chức năng sản xuất chưa được khởi tạo. Cần migration và quyền sản xuất.</p>;
 const filtered=orders.filter(o=>(!project||o.project_id===project)&&(!status||o.status===status)&&(!keyword||`${o.code} ${o.title} ${o.project_name}`.toLowerCase().includes(keyword.toLowerCase())));
 const visibleBoms=meta.boms.filter((b:any)=>(!project||b.project_id===project));
 return <div className="p-3 space-y-3 text-xs">
  <div className="flex flex-wrap justify-between items-center gap-2"><span className="text-slate-600">Sản xuất & Thi công / Sản xuất</span><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>load()}>Làm mới</Button>{meta.capabilities['production_order.create'] && <Button size="sm" disabled={!project} onClick={()=>setDraft(true)}>Lập lệnh sản xuất</Button>}</div></div>
  <div className="flex gap-2 border-b">{[['orders','Lệnh sản xuất'],['bom','BOM dự án'],['representatives','Gán vật tư đại diện']].map(([key,name])=><button key={key} onClick={()=>setTab(key)} className={`px-3 py-2 border-b-2 ${tab===key?'border-blue-600 text-blue-700':'border-transparent text-slate-500'}`}>{name}</button>)}</div>
  <div className="flex flex-wrap gap-2"><select aria-label="Dự án sản xuất" className={`${fieldClass} max-w-96`} value={project} onChange={e=>{setProject(e.target.value);setProof('');}}><option value="">Tất cả dự án</option>{meta.projects.map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select>{tab==='orders' && <><input aria-label="Tìm lệnh" className={`${fieldClass} max-w-72`} placeholder="Tìm mã lệnh / dự án" value={keyword} onChange={e=>setKeyword(e.target.value)}/><select className={`${fieldClass} max-w-48`} aria-label="Trạng thái lệnh" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Mọi trạng thái</option>{['draft','released','in_progress','completed','cancelled'].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></>}</div>
  {tab==='orders' && <DataTable<any> data={filtered} keyExtractor={o=>o.id} searchValue={keyword} onSearchChange={setKeyword} onRefresh={load} defaultShowStats={false} columns={[
   {id:'code',header:'Mã lệnh',accessorKey:'code',cell:o=><Link className="text-blue-600" href={`/san-xuat/${o.id}`}>{o.code}</Link>},
   {id:'title',header:'Tên lệnh',accessorKey:'title'},
   {id:'project',header:'Dự án',cell:o=><span>{o.project_code} · {o.project_name}</span>},
   {id:'lines',header:'Hạng mục',accessorKey:'line_count',align:'center'},
   {id:'status',header:'Trạng thái',cell:o=>statusLabels[o.status]},
   {id:'due',header:'Hạn hoàn thành',cell:o=>o.due_at?new Date(o.due_at).toLocaleString('vi-VN'):'—'}
  ]}/>}
  {tab==='bom' && <><div className="flex justify-end">{meta.capabilities['production_order.create'] && <Button size="sm" disabled={!project} onClick={()=>setCreateBom(true)}>Lập BOM từ maket đã duyệt</Button>}</div><div className="overflow-x-auto border rounded"><table className="w-full"><thead className="bg-slate-100"><tr>{['Mã BOM','Tên','Phiên bản','Gán vật tư','Trạng thái',''].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{visibleBoms.map((b:any)=><tr key={b.id} className="border-t"><td className="p-2">{b.code}</td><td className="p-2 max-w-96 truncate" title={b.title}>{b.title}</td><td className="p-2">{b.revision_no}</td><td className="p-2">{b.mapped?'Đã gán':'Cần hoàn thiện'}</td><td className="p-2">{statusLabels[b.status] || b.status}</td><td className="p-2"><Button variant="ghost" size="sm" onClick={()=>setEditor(b.id)}>Xem / Sửa</Button></td></tr>)}</tbody></table></div></>}
  {tab==='representatives' && <><div className="flex justify-end"><Button size="sm" disabled={!meta.capabilities['item.update']} onClick={()=>setRepVariant(true)}>Thêm quy cách đại diện</Button></div><p className="text-slate-500">Gán mặc định được dùng khi lập BOM mới; BOM đã có không bị thay đổi. Hệ số nhân dùng cho lượng tính theo diện tích/chu vi.</p><div className="overflow-x-auto border rounded"><table className="w-full"><thead className="bg-slate-100"><tr>{['Đại diện / Quy cách','Cách tính','Vật tư mặc định','Đơn vị','Hệ số','Hao hụt %',''].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{meta.representatives.map((r:any,index:number)=>{const item=meta.items.find((i:any)=>i.id===r.default_item_id);const update=(v:any)=>setMeta((m:any)=>({...m,representatives:m.representatives.map((x:any,n:number)=>n===index?{...x,...v}:x)}));return <tr key={r.id} className="border-t"><td className="p-2">{r.name}<span className="block text-slate-500">{r.specification_key || 'Mặc định'}</span></td><td className="p-1"><select className={fieldClass} value={r.quantity_basis} onChange={e=>update({quantity_basis:e.target.value})}>{[['area','Diện tích'],['perimeter','Chu vi'],['count','Số lượng'],['manual','Nhập tay']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></td><td className="p-1 min-w-64"><select className={fieldClass} aria-label={`Gán ${r.code} ${r.specification_key}`} value={r.default_item_id || ''} onChange={e=>update({default_item_id:e.target.value,default_unit_id:''})}><option value="">Chưa gán</option>{meta.items.filter((i:any)=>i.isActive).map((i:any)=><option key={i.id} value={i.id}>{i.code} · {i.name}</option>)}</select></td><td className="p-1"><select className={fieldClass} value={r.default_unit_id || ''} onChange={e=>update({default_unit_id:e.target.value})}><option value="">Chọn đơn vị</option>{item?.conversions.map((u:any)=><option key={u.unitId} value={u.unitId}>{u.unitName}</option>)}</select></td><td className="p-1 w-20"><input className={fieldClass} type="number" min="0.000001" step="any" value={r.rules?.coefficient ?? 1} onChange={e=>update({rules:{...r.rules,coefficient:Number(e.target.value)}})}/></td><td className="p-1 w-20"><input className={fieldClass} type="number" min="0" max="100" step="any" value={r.rules?.wasteRate || 0} onChange={e=>update({rules:{...r.rules,wasteRate:Number(e.target.value)}})}/></td><td className="p-1"><Button size="sm" disabled={busy || !meta.capabilities['item.update']} onClick={()=>run(async()=>{await mutate('/api/material-representatives',{id:r.id,defaultItemId:r.default_item_id,defaultUnitId:r.default_unit_id,quantityBasis:r.quantity_basis,rules:r.rules},'PUT');toast.success('Đã nhớ gán mặc định');})}>Lưu gán</Button></td></tr>;})}</tbody></table></div></>}
  <Modal isOpen={Boolean(editor)} onClose={()=>setEditor('')} title="BOM dự án · Gán vật tư và NVL cấu thành" maxWidth="6xl">{editor && <BomEditor id={editor} meta={meta} onSaved={id=>{setEditor(id);void load();}}/>}</Modal>
  <Modal isOpen={draft} onClose={()=>setDraft(false)} title="Lệnh sản xuất nhiều hạng mục" maxWidth="6xl">{draft && <OrderDraft meta={meta} projectId={project} onSaved={id=>{window.location.href=`/san-xuat/${id}`;}}/>}</Modal>
  <Modal isOpen={createBom} onClose={()=>setCreateBom(false)} title="Lập BOM từ maket đã duyệt" maxWidth="lg"><label className="block text-xs">Maket thuộc dự án<select className={fieldClass} aria-label="Maket lập BOM" value={proof} onChange={e=>setProof(e.target.value)}><option value="">Chọn maket</option>{meta.designs.filter((d:any)=>d.project_id===project).map((d:any)=><option key={d.id} value={d.id}>{d.code} · {d.title} · PA {d.version_no}</option>)}</select></label><div className="mt-3 flex justify-end"><Button disabled={!proof || busy} onClick={()=>run(async()=>{const r=await mutate('/api/bom/from-design',{projectId:project,designProofId:proof});setCreateBom(false);await load();setEditor(r.bomId);toast.success('Đã lấy khảo sát và maket; kiểm tra định mức rồi gán vật tư');})}>Lập BOM</Button></div></Modal>
  <Modal isOpen={repVariant} onClose={()=>setRepVariant(false)} title="Quy cách đại diện" maxWidth="lg"><div className="grid gap-2 text-xs"><label>Nhóm đại diện<select className={fieldClass} value={variant.code} onChange={e=>setVariant({...variant,code:e.target.value})}>{['frame','face','letters','logo','color_strip','lighting','power','accessories','other'].map(c=><option key={c} value={c}>{meta.representatives.find((r:any)=>r.code===c)?.name || c}</option>)}</select></label><label>Tên quy cách<input className={fieldClass} value={variant.name} onChange={e=>setVariant({...variant,name:e.target.value})}/></label><label>Khóa quy cách (khớp vật liệu maket)<input className={fieldClass} value={variant.specificationKey} onChange={e=>setVariant({...variant,specificationKey:e.target.value})}/></label><label>Cách tính<select className={fieldClass} value={variant.quantityBasis} onChange={e=>setVariant({...variant,quantityBasis:e.target.value})}>{['area','perimeter','count','manual'].map(v=><option key={v} value={v}>{v}</option>)}</select></label><Button disabled={busy} onClick={()=>run(async()=>{await mutate('/api/material-representatives',variant);setRepVariant(false);await load();toast.success('Đã thêm quy cách');})}>Thêm</Button></div></Modal>
 </div>;
}
