-- Do not expose ERP/IAM or auth credentials through the Supabase Data API.
-- Flush deferred SELECTED-scope checks before changing table security metadata.
SET CONSTRAINTS ALL IMMEDIATE;
REVOKE ALL ON SCHEMA erp,iam FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA erp,iam FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA erp,iam FROM PUBLIC;
ALTER TABLE erp.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.organizations USING (id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.memberships USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.departments FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.departments USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.teams FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.teams USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.employees FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.employees USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.team_members FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.team_members USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.employee_private_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.employee_private_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.employee_private_profiles USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.partners FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.partners USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.partner_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.partner_contacts FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.partner_contacts USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.partner_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.partner_terms FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.partner_terms USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.partner_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.partner_activities FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.partner_activities USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.units FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.units USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.item_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.item_categories FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.item_categories USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.items FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.items USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.item_unit_conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.item_unit_conversions FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.item_unit_conversions USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.supplier_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.supplier_prices FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.supplier_prices USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.vehicles FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.vehicles USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.warehouses FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.warehouses USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.warehouse_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.warehouse_members FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.warehouse_members USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.warehouse_item_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.warehouse_item_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.warehouse_item_settings USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.project_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.project_templates FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.project_templates USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.project_template_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.project_template_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.project_template_versions USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.projects FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.projects USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.project_members FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.project_members USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.tasks USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.task_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.task_assignees FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.task_assignees USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.report_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.report_templates FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.report_templates USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.report_template_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.report_template_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.report_template_versions USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.report_template_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.report_template_bindings FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.report_template_bindings USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.work_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.work_reports FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.work_reports USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.report_labor_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.report_labor_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.report_labor_entries USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.report_material_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.report_material_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.report_material_usage USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.production_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.production_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.production_orders USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.production_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.production_materials FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.production_materials USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.production_outputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.production_outputs FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.production_outputs USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.quotations FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.quotations USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.quotation_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.quotation_revisions FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.quotation_revisions USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.quotation_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.quotation_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.quotation_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.estimate_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.estimate_components FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.estimate_components USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.sales_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.sales_orders USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.sales_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.sales_order_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.sales_order_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.purchase_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.purchase_orders USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.purchase_order_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.purchase_order_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.contracts FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.contracts USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.contract_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.contract_milestones FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.contract_milestones USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_lots FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_lots USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_documents FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_documents USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_document_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_document_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_document_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_postings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_postings FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_postings USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_movements FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_movements USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_balances FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_balances USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.stock_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.stock_reservations FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.stock_reservations USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.inventory_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.inventory_counts FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.inventory_counts USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.inventory_count_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.inventory_count_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.inventory_count_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.cash_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.cash_accounts FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.cash_accounts USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.open_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.open_items FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.open_items USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.payments FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.payments USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.open_item_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.open_item_adjustments FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.open_item_adjustments USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.payment_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.payment_allocations FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.payment_allocations USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.cash_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.cash_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.cash_entries USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.expense_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.expense_claims FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.expense_claims USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.expense_claim_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.expense_claim_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.expense_claim_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.expense_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.expense_settlements FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.expense_settlements USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.project_cost_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.project_cost_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.project_cost_entries USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.period_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.period_locks FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.period_locks USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.trips FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.trips USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.trip_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.trip_stops FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.trip_stops USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.trip_stock_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.trip_stock_documents FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.trip_stock_documents USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.field_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.field_events FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.field_events USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.acceptances ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.acceptances FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.acceptances USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.attendance_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.attendance_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.attendance_entries USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.attendance_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.attendance_periods FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.attendance_periods USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.salary_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.salary_terms FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.salary_terms USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.payroll_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.payroll_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.payroll_runs USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.payroll_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.payroll_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.payroll_lines USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.payroll_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.payroll_payments FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.payroll_payments USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.files FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.files USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.record_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.record_files FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.record_files USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.ai_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.ai_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.ai_runs USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.ai_run_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.ai_run_files FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.ai_run_files USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.approval_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.approval_policies FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.approval_policies USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.approval_policy_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.approval_policy_steps FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.approval_policy_steps USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.approval_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.approval_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.approval_requests USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.approval_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.approval_decisions FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.approval_decisions USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.audit_events USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.idempotency_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.idempotency_keys USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.outbox_events FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.outbox_events USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.number_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.number_sequences FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.number_sequences USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE erp.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp.company_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON erp.company_settings USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.permissions FORCE ROW LEVEL SECURITY;
CREATE POLICY catalog_read ON iam.permissions FOR SELECT USING (true);
ALTER TABLE iam.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.roles FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.roles USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.role_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.role_grants FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.role_grants USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.grant_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.grant_projects FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.grant_projects USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.grant_warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.grant_warehouses FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.grant_warehouses USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.grant_departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.grant_departments FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.grant_departments USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.user_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.user_roles USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.role_change_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.role_change_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.role_change_requests USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
ALTER TABLE iam.permission_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.permission_dependencies FORCE ROW LEVEL SECURITY;
CREATE POLICY catalog_read ON iam.permission_dependencies FOR SELECT USING (true);
ALTER TABLE iam.resource_projections ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.resource_projections FORCE ROW LEVEL SECURITY;
CREATE POLICY catalog_read ON iam.resource_projections FOR SELECT USING (true);
ALTER TABLE iam.role_read_projections ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.role_read_projections FORCE ROW LEVEL SECURITY;
CREATE POLICY organization_isolation ON iam.role_read_projections USING (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK (organization_id = nullif(current_setting('app.organization_id',true),'')::uuid);
DO $access$
DECLARE r text; t text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
    IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN
      EXECUTE format('REVOKE ALL ON SCHEMA erp,iam FROM %I',r);
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA erp,iam FROM %I',r);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA erp,iam FROM %I',r);
      FOREACH t IN ARRAY ARRAY['user','session','account','verification'] LOOP
        EXECUTE format('REVOKE ALL ON public.%I FROM %I',t,r);
      END LOOP;
    END IF;
  END LOOP;
END $access$;
-- Runtime DB role/provisioning and server authorization are intentionally not enabled by this installer.
