'use client';
import {useSetPageHeader} from '@/contexts/page-header-context';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button,toast} from '@/components/ui';
import {readJson,useWorkflowMutation,fieldClass,statusLabels} from '@/components/production/client';
import {StockDocuments} from '@/components/production/StockDocuments';
export default function ProductionSales(){
 const [meta,setMeta]=useState<any>(null),[project,setProject]=useState(''),[production,setProduction]=useState(''),[orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[selected,setSelected]=useState<any[]>([]),[saleId,setSaleId]=useState(''),[sale,setSale]=useState<any>(null),[ar,setAr]=useState(false),[days,setDays]=useState(15),[error,setError]=useState('');
 useSetPageHeader({title:"Bán hàng",subtitle:"Thành phẩm theo lô sản xuất",screenCode:"M04"},[]);
 const {busy,mutate,run}=useWorkflowMutation();
 async function loadSale(id=saleId){if(id)setSale((await readJson(`/api/crm/orders/${id}`)).order);}
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setProject(q.get('projectId') || '');setProduction(q.get('productionOrderId') || '');const sid=q.get('orderId') || '';setSaleId(sid);readJson('/api/production-orders/metadata').then(setMeta).catch(e=>setError(e.message));if(sid)loadSale(sid).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!project){setProducts([]);return;}setSelected([]);Promise.all([meta?.capabilities?.["production_order.read"]?readJson(`/api/production-orders?projectId=${project}`):Promise.resolve({orders:[]}),readJson(`/api/production-orders/available-products?projectId=${project}${production?`&productionOrderId=${production}`:''}`)]).then(([o,p])=>{setOrders(o.orders);setProducts(p.products);setError('');}).catch(e=>setError(e.message));},[project,production,meta]);
 if(error)return <div className="p-4 text-sm text-red-600" role="alert">{error}<Link className="block text-blue-600" href="/ban-hang">Về bán hàng</Link></div>;
 if(!meta)return <p className="p-4 text-xs">Đang tải thành phẩm…</p>;
 if(!meta.ready)return <p className="p-4 text-xs">Chức năng sản xuất chưa được khởi tạo.</p>;
 const caps=meta.capabilities;
 return <div className="p-3 text-xs space-y-3"><div className="flex justify-between"><h1 className="text-lg font-semibold">Bán thành phẩm theo dự án / lệnh sản xuất</h1><Link href="/ban-hang" className="text-blue-600">Danh sách đơn bán</Link></div>
 {saleId && sale?<><div className="flex gap-3 items-center"><strong>{sale.code} · {statusLabels[sale.status]}</strong><span>{Number(sale.total).toLocaleString('vi-VN')} đ</span>{['submitted','approved'].includes(sale.status) && caps['sales_order.approve'] && <Button disabled={busy} size="sm" onClick={()=>run(async()=>{await mutate(`/api/crm/orders/${sale.id}/actions`,{action:'approve'});await loadSale();toast.success('Đã giữ đúng lô và tạo phiếu xuất chờ duyệt');})}>Duyệt đơn / Tạo phiếu xuất</Button>}{['submitted','approved'].includes(sale.status) && caps['sales_order.cancel'] && <Button size="sm" disabled={busy} variant="secondary" onClick={()=>run(async()=>{await mutate(`/api/crm/orders/${sale.id}/actions`,{action:'cancel'});await loadSale();toast.success('Đã hủy và giải phóng hàng giữ');})}>Hủy đơn chưa giao</Button>}</div><table className="w-full border"><thead className="bg-slate-100"><tr>{['Thành phẩm','Mã lô','Số lượng','Đã giao','Đơn vị','Giá bán'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{sale.lines.map((l:any)=><tr key={l.id} className="border-t"><td className="p-2">{l.description} · {l.item_code}</td><td>{l.lot_code}</td><td>{Number(l.qty)}</td><td>{Number(l.delivered_qty)}</td><td>{l.unit_name}</td><td>{Number(l.unit_price).toLocaleString('vi-VN')}</td></tr>)}</tbody></table><StockDocuments documents={sale.documents} capabilities={caps} onChanged={()=>loadSale()}/><Button variant="secondary" size="sm" onClick={()=>{setSaleId('');setSale(null);}}>Lập đơn khác</Button></>:<>
 <div className="flex gap-2"><select aria-label="Dự án bán thành phẩm" className={`${fieldClass} max-w-96`} value={project} onChange={e=>{setProject(e.target.value);setProduction('');}}><option value="">Chọn dự án</option>{meta.projects.map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><select aria-label="Lệnh sản xuất bán" className={`${fieldClass} max-w-80`} value={production} onChange={e=>setProduction(e.target.value)}><option value="">Mọi lệnh của dự án</option>{orders.map(o=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></div>
 <p className="text-slate-500">Chọn từng lô đã nhập kho. Mỗi lô gắn riêng với hạng mục và maket; lượng còn bán đã trừ hàng được giữ.</p>
 <div className="overflow-x-auto border rounded"><table className="w-full"><thead className="bg-slate-100"><tr>{['Chọn','Hạng mục / Mã hàng','Maket','Lệnh','Lô','Kho','Còn bán','Đơn vị'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{products.map(p=>{const key=`${p.lot_id}:${p.warehouse_id}`;return <tr key={key} className="border-t"><td className="p-2"><input aria-label={`Chọn lô ${p.lot_code}`} type="checkbox" checked={selected.some(s=>s.key===key)} onChange={e=>setSelected(ls=>e.target.checked?[...ls,{...p,key,qty:0,unitPrice:0}]:ls.filter(s=>s.key!==key))}/></td><td>{p.line_title} · {p.item_code}</td><td>{p.design_snapshot?.design?.proof?.code || p.design_proof_id}</td><td>{p.production_code}</td><td>{p.lot_code}</td><td>{p.warehouse_name}</td><td>{Number(p.available_qty)}</td><td>{p.unit_name}</td></tr>;})}</tbody></table>{!products.length && <p className="p-4 text-slate-500">Chưa có thành phẩm khả dụng đã nhập kho của lựa chọn này.</p>}</div>
 {!!selected.length && <table className="w-full border"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Lô bán</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{selected.map((s,n)=><tr key={s.key} className="border-t"><td className="p-2">{s.line_title} · {s.lot_code}</td>{['qty','unitPrice'].map(k=><td key={k} className="p-1"><input aria-label={`${k==='qty'?'Lượng':'Giá'} ${s.lot_code}`} className={fieldClass} type="number" min="0" max={k==='qty'?Number(s.available_qty):undefined} step="any" value={s[k]} onChange={e=>setSelected(ls=>ls.map((v,i)=>i===n?{...v,[k]:Number(e.target.value)}:v))}/></td>)}<td className="text-center">{(s.qty*s.unitPrice).toLocaleString('vi-VN')}</td></tr>)}</tbody></table>}
 <div className="flex items-center gap-3"><label className="flex gap-2"><input type="checkbox" checked={ar} onChange={e=>setAr(e.target.checked)}/>Ghi nhận công nợ một lần theo đơn bán</label>{ar && <label>Hạn thanh toán (ngày)<input className={`${fieldClass} max-w-24`} type="number" min="1" value={days} onChange={e=>setDays(Number(e.target.value))}/></label>}<Button className="ml-auto" size="sm" disabled={busy || !selected.length || !caps['sales_order.create']} onClick={()=>run(async()=>{const customerId=meta.projects.find((p:any)=>p.id===project)?.customer_id;const r=await mutate('/api/crm/orders',{projectId:project,productionOrderId:production || undefined,customerId,recordReceivable:ar,paymentDays:days,lines:selected.map(s=>({itemId:s.item_id,unitId:s.base_unit_id,lotId:s.lot_id,warehouseId:s.warehouse_id,productionOrderLineId:s.production_order_line_id,qty:s.qty,unitPrice:s.unitPrice}))});const id=r.orderId || r.order?.id;setSaleId(id);await loadSale(id);toast.success('Đã tạo đơn bán chờ duyệt');})}>Lập đơn bán chờ duyệt</Button></div>
 </>}
 </div>;
}
